[project]
name = "Sammie-Roto-2"
version = "2.4.1"
description = "Sammie Roto 2 application"
requires-python = ">=3.12"

dependencies = [
    "opencv-python~=4.14",
    "PySide6-essentials==6.9.3",
    "av~=18.1",
    "requests~=2.34",
    "tqdm~=4.70",
    "OpenEXR~=3.4",
    "diffusers~=0.39",
    "einops~=0.8",
    "opencolorio~=2.5",
]

[project.optional-dependencies]
cpu   = ["torch==2.11.0", "torchvision==0.26.0", "accelerate~=1.14"]
cu126 = ["torch==2.11.0", "torchvision==0.26.0", "accelerate~=1.14"]
cu130 = ["torch==2.11.0", "torchvision==0.26.0", "accelerate~=1.14"]
rocm  = [
    "torch==2.11.0 ; sys_platform == 'linux'",
    "torchvision==0.26.0 ; sys_platform == 'linux'",
    "triton-rocm==3.6.0 ; sys_platform == 'linux'",
    "torch==2.9.1+rocm7.2.1 ; sys_platform == 'win32'",
    "torchvision==0.24.1+rocm7.2.1 ; sys_platform == 'win32'",
    "rocm-sdk-core==7.2.1 ; sys_platform == 'win32'",
    "rocm-sdk-devel==7.2.1 ; sys_platform == 'win32'",
    "rocm-sdk-libraries-custom==7.2.1 ; sys_platform == 'win32'",
    "rocm==7.2.1 ; sys_platform == 'win32'",
    "accelerate~=1.14"
]
xpu   = ["torch==2.11.0", "torchvision==0.26.0", "triton-xpu==3.7.0", "accelerate~=1.14"]

[tool.uv]
package = false
conflicts = [
  [
    { extra = "cpu" },
    { extra = "cu126" },
    { extra = "cu130" },
    { extra = "rocm" },
    { extra = "xpu" },
  ],
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu130", extra = "cu130" },
  { index = "pytorch-cu126", extra = "cu126" },
  { index = "pytorch-rocm",  extra = "rocm", marker = "sys_platform == 'linux'" },
  { url = "https://repo.radeon.com/rocm/windows/rocm-rel-7.2.1/torch-2.9.1%2Brocm7.2.1-cp312-cp312-win_amd64.whl", extra = "rocm", marker = "sys_platform == 'win32'" },
  { index = "pytorch-xpu",   extra = "xpu" },
  { index = "pytorch-cpu",   extra = "cpu" },
]
torchvision = [
  { index = "pytorch-cu130", extra = "cu130" },
  { index = "pytorch-cu126", extra = "cu126" },
  { index = "pytorch-rocm",  extra = "rocm", marker = "sys_platform == 'linux'"  },
  { url = "https://repo.radeon.com/rocm/windows/rocm-rel-7.2.1/torchvision-0.24.1%2Brocm7.2.1-cp312-cp312-win_amd64.whl", extra = "rocm", marker = "sys_platform == 'win32'" },
  { index = "pytorch-xpu",   extra = "xpu" },
  { index = "pytorch-cpu",   extra = "cpu" },
]
triton-rocm = [
  { index = "pytorch-rocm", marker = "sys_platform == 'linux'" },
]
triton-xpu = [
  { index = "pytorch-xpu" },
]
rocm-sdk-core = [
  { url = "https://repo.radeon.com/rocm/windows/rocm-rel-7.2.1/rocm_sdk_core-7.2.1-py3-none-win_amd64.whl", extra = "rocm", marker = "sys_platform == 'win32'" },
]
rocm-sdk-devel = [
  { url = "https://repo.radeon.com/rocm/windows/rocm-rel-7.2.1/rocm_sdk_devel-7.2.1-py3-none-win_amd64.whl", extra = "rocm", marker = "sys_platform == 'win32'" },
]
rocm-sdk-libraries-custom = [
  { url = "https://repo.radeon.com/rocm/windows/rocm-rel-7.2.1/rocm_sdk_libraries_custom-7.2.1-py3-none-win_amd64.whl", extra = "rocm", marker = "sys_platform == 'win32'" },
]
rocm = [
  { url = "https://repo.radeon.com/rocm/windows/rocm-rel-7.2.1/rocm-7.2.1.tar.gz", extra = "rocm", marker = "sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[[tool.uv.index]]
name = "pytorch-rocm"
url = "https://download.pytorch.org/whl/rocm7.2"
explicit = true

[[tool.uv.index]]
name = "pytorch-xpu"
url = "https://download.pytorch.org/whl/xpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true